Remove vserver support (fixes #11289)
This is probably completely unused by now, as vservers have been
superseeded by alternative technology for many years already.

diff --git a/handlers/mysql.in b/handlers/mysql.in
--- a/handlers/mysql.in
+++ b/handlers/mysql.in
@@ -13,7 +13,6 @@ getconf hotcopy no
 getconf sqldump no
 getconf sqldumpoptions "--lock-tables --complete-insert --add-drop-table --quick --quote-names"
 getconf compress yes
-getconf vsname
 
 # authentication:
 getconf user
@@ -21,27 +20,6 @@ getconf dbusername
 getconf dbpassword
 getconf configfile /etc/mysql/debian.cnf
 
-
-# Decide if the handler should operate on a vserver or on the host.
-# In the former case, check that $vsname exists and is running.
-usevserver=no
-vroot=''
-if [ $vservers_are_available = yes ]; then
-   if [ -n "$vsname" ]; then
-      # does it exist ?
-      if ! vservers_exist "$vsname" ; then
-         fatal "The vserver given in vsname ($vsname) does not exist."
-      fi
-      # is it running ?
-      vservers_running $vsname || fatal "The vserver $vsname is not running."
-      # everything ok
-      info "Using vserver '$vsname'."
-      usevserver=yes
-      vroot="$VROOTDIR/$vsname"
-   else
-      info "No vserver name specified, actions will be performed on the host."
-   fi
-fi
 
 ## Prepare ignore part of the command
 ## This only works for mysqldump at the moment
@@ -51,21 +29,15 @@ for i in $ignores $nodata; do
    ignore="$ignore --ignore-table=$i"
 done
 
-# create backup dirs, $vroot will be empty if no vsname was specified
+# create backup dirs
 # and we will instead proceed to operate on the host
-[ -d $vroot$backupdir ] || mkdir -p $vroot$backupdir
-[ -d $vroot$backupdir ] || fatal "Backup directory '$vroot$backupdir'"
+[ -d $backupdir ] || mkdir -p $backupdir
+[ -d $backupdir ] || fatal "Backup directory '$backupdir'"
 hotdir="$backupdir/hotcopy"
 dumpdir="$backupdir/sqldump"
 
-if [ $usevserver = yes ]
-then
-   [ "$sqldump" == "no" -o -d $vroot$dumpdir ] || $VSERVER $vsname exec mkdir -p $dumpdir
-   [ "$hotcopy" == "no" -o -d $vroot$hotdir ] || $VSERVER $vsname exec mkdir -p $hotdir
-else
-   [ "$sqldump" == "no" -o -d $dumpdir ] || mkdir -p $dumpdir
-   [ "$hotcopy" == "no" -o -d $hotdir ] || mkdir -p $hotdir
-fi
+[ "$sqldump" == "no" -o -d $dumpdir ] || mkdir -p $dumpdir
+[ "$hotcopy" == "no" -o -d $hotdir ] || mkdir -p $hotdir
 
 #######################################################################
 ## AUTHENTICATION
@@ -88,23 +60,13 @@ defaultsfile=""
 
 if [ -n "$dbusername" -a -n "$dbpassword" ]
 then
-   if [ $usevserver = yes ]
-   then
-      home=`$VSERVER $vsname exec getent passwd "root" | @AWK@ -F: '{print $6}'`
-   else
-      home=`getent passwd "root" | @AWK@ -F: '{print $6}'`
-   fi
+   home=`getent passwd "root" | @AWK@ -F: '{print $6}'`
 
    [ -d $home ] || fatal "Can't find root's home directory ($home)."
     
    mycnf="$home/.my.cnf"
 
-   if [ $usevserver = yes ]
-   then
-      workcnf="$vroot$mycnf"
-   else
-      workcnf="$mycnf"
-   fi
+   workcnf="$mycnf"
 
    if [ -f $workcnf ]
    then
@@ -145,28 +107,18 @@ EOF
 elif [ -n "$user" ]
 then
    userset=true;
-   if [ $usevserver = yes ]
+
+   userhome=`getent passwd "$user" | @AWK@ -F: '{print $6}'`
+   if [ $? -eq 2 ]
    then
-      userhome=`$VSERVER $vsname exec getent passwd "$user" | @AWK@ -F: '{print $6}'`
-      if [ $? -eq 2 ]
-      then
-	 fatal "User $user not found in /etc/passwd"
-      fi
-      debug "User home set to: $vroot$userhome"
-      [ -f $vroot$userhome/.my.cnf ] || fatal "Can't find config file in $userhome/.my.cnf"
-   else
-      userhome=`getent passwd "$user" | @AWK@ -F: '{print $6}'`
-      if [ $? -eq 2 ]
-      then
-	 fatal "User $user not found in /etc/passwd"
-      fi
-      debug "User home set to: $userhome"
-      [ -f $userhome/.my.cnf ] || fatal "Can't find config file in $userhome/.my.cnf"
+      fatal "User $user not found in /etc/passwd"
    fi
-	
+   debug "User home set to: $userhome"
+   [ -f $userhome/.my.cnf ] || fatal "Can't find config file in $userhome/.my.cnf"
+
    defaultsfile="--defaults-extra-file=$userhome/.my.cnf"
    debug "using $defaultsfile"
-# otherwise use $configfile
+   # otherwise use $configfile
 else
    user=root
    defaultsfile="--defaults-extra-file=$configfile"
@@ -180,13 +132,7 @@ then
    info "Initializing hotcopy method"
    if [ "$databases" == "all" ]
    then
-      if [ $usevserver = yes ]
-      then
-         info "dbhost: $dbhost"
-         execstr="$VSERVER $vsname exec $MYSQLHOTCOPY -h $dbhost --quiet --allowold --regexp /.\*/./.\*/ $hotdir"
-      else
-         execstr="$MYSQLHOTCOPY --quiet --allowold --regexp /.\*/./.\*/ $hotdir"
-      fi
+      execstr="$MYSQLHOTCOPY --quiet --allowold --regexp /.\*/./.\*/ $hotdir"
       debug "su $user -c \"$execstr\""
       if [ ! $test ]
       then
@@ -204,12 +150,7 @@ then
    else
       for db in $databases
       do
-         if [ $usevserver = yes ]
-         then
-            execstr="$VSERVER $vsname exec $MYSQLHOTCOPY --allowold $db $hotdir"
-         else
-            execstr="$MYSQLHOTCOPY --allowold $db $hotdir"
-         fi
+         execstr="$MYSQLHOTCOPY --allowold $db $hotdir"
          debug 'su $user -c \"$execstr\"'
          if [ ! $test ]
          then
@@ -236,20 +177,10 @@ then
    info "Initializing SQL dump method"
    if [ "$databases" == "all" ]
    then
-      if [ $usevserver = yes ]
+      databases=$(set -o pipefail ; su $user -c "$MYSQL $defaultsfile -N -B -e 'show databases'" | sed 's/|//g;/\+----/d;/^\(information\|performance\)_schema$/d')
+      if [ $? -ne 0 ]
       then
-         debug 'set -o pipefail ; echo show databases | $VSERVER $vsname exec su $user -c \"$MYSQL $defaultsfile\" | grep -v Database | grep -v '"'"'^\(information\|performance\)_schema$'"'"
-         databases=`set -o pipefail ; echo 'show databases' | $VSERVER $vsname exec su $user -c "$MYSQL $defaultsfile" | grep -v Database | grep -v '^\(information\|performance\)_schema$'`
-         if [ $? -ne 0 ]
-         then
-            fatal "Authentication problem, maybe user/password is wrong or mysqld is not running?"
-         fi
-      else
-         databases=$(set -o pipefail ; su $user -c "$MYSQL $defaultsfile -N -B -e 'show databases'" | sed 's/|//g;/\+----/d;/^\(information\|performance\)_schema$/d')
-         if [ $? -ne 0 ]
-         then
-            fatal "Authentication problem, maybe user/password is wrong or mysqld is not running?"
-         fi
+         fatal "Authentication problem, maybe user/password is wrong or mysqld is not running?"
       fi
    fi
 
@@ -275,31 +206,19 @@ then
          done
          DUMP="( $DUMP; $DUMP_STRUCT )"
       fi
-      if [ $usevserver = yes ]
-      then
-         # Test to make sure mysqld is running, if it is not sqldump will not work
-         $VSERVER $vsname exec su $user -c "$MYSQLADMIN $defaultsfile ping 2>&1 >/dev/null"
-         if [ $? -ne 0 ]; then
-            fatal "mysqld doesn't appear to be running!"
-         fi
-         if [ "$compress" == "yes" ]; then
-            execstr="$VSERVER $vsname exec $DUMP | $GZIP $GZIP_OPTS > '$vroot$dumpdir/${db}.sql.gz'"
-         else
-            execstr="$VSERVER $vsname exec $DUMP -r '$vroot$dumpdir/${db}.sql'"
-         fi
+
+      # Test to make sure mysqld is running, if it is not sqldump will not work
+      su $user -c "$MYSQLADMIN $defaultsfile ping 2>&1 >/dev/null"
+      if [ $? -ne 0 ]; then
+         fatal "mysqld doesn't appear to be running!"
+      fi
+      if [ "$compress" == "yes" ]; then
+         execstr="$DUMP | $GZIP $GZIP_OPTS > '$dumpdir/${db}.sql.gz'"
       else
-         # Test to make sure mysqld is running, if it is not sqldump will not work
-         su $user -c "$MYSQLADMIN $defaultsfile ping 2>&1 >/dev/null"
-         if [ $? -ne 0 ]; then
-            fatal "mysqld doesn't appear to be running!"
-         fi
-         if [ "$compress" == "yes" ]; then
-            execstr="$DUMP | $GZIP $GZIP_OPTS > '$dumpdir/${db}.sql.gz'"
-         else
-            execstr="$DUMP > '$dumpdir/${db}.sql'"
-         fi
+         execstr="$DUMP > '$dumpdir/${db}.sql'"
       fi
       debug "su $user -c \"$execstr\""
+
       if [ ! $test ]
       then
          output=`su $user -s /bin/bash -c "set -o pipefail ; $execstr" 2>&1`
