exit with non-zero exit code in case of problems, fixes #8279
 * 0 for success
 * 1 for errors or warnings if reportwarning enabled
 * 2 for fatal errors and halts

diff --git a/src/backupninja.in b/src/backupninja.in
--- a/src/backupninja.in
+++ b/src/backupninja.in
@@ -648,3 +648,11 @@ if [ -n "$reporthost" ]; then
    debug "send $logfile to $reportuser@$reporthost:$reportdirectory"
    rsync -qt $logfile $reportuser@$reporthost:$reportdirectory
 fi
+
+# return exit code
+[ $halts == 0 ] || exit 2
+[ $fatals == 0 ] || exit 2
+[ $errors == 0 ] || exit 1
+[ "$reportwarning" == "yes" -a $warnings != 0 ] && exit 1
+
+exit 0
